# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c570231e13dfb50e831d4ecac96ce36ec18f64e4d0ff3b32a8dbab2a5619dd2667e85e97e689be1542cc9edc4fc1cc2be3fb12c15bf2d4ae2fc3d47ed6fc7c4e

test:
  secret_key_base: 3c41811df37e5f57f26769bd7fe786b905d100be57e81eea8c830d23012f93ed92a086e030c079b7088b91620c0d36d91329a75391bffd54fd84ab5fc51ca8e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
